[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.13"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
eth = "${ETH_RPC_URL}"

[etherscan]
eth = { key = "${ETHERSCAN_API_KEY}" }
